#!/usr/bin/env bash

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTCONFIG=$HOME/.config
DOTFILES=$HOME/.dotfiles
DOTLOCAL=$HOME/.local/share/dotfiles

GITCLONE="git clone --depth=1"

cd "$HOME" || exit
rm -rf "$DOTFILES"
mkdir "$DOTFILES"
cd "$DOTFILES" || exit

git clone git@github.com:shawnmaust/dotfiles.git .

rm -rf \
  "$DOTCONFIG/nvim/init.vim" \
  "$DOTFZF" \
  "$DOTLOCAL" \
  "$HOME/.bashrc" \
  "$HOME/.gitconfig" \
  "$HOME/.screenrc" \
  "$HOME/.vim" \
  "$HOME/.vimrc" \
  "$HOME/.zshrc"

mkdir -p \
  "$DOTCONFIG/nvim" \
  "$DOTLOCAL" \
  "$HOME/.local/share/vim/"{swap,undo} \
  "$HOME/.vim/colors" \
  "$HOME/.vim/pack/plugins/start"

ln -s "$DOTFILES/bashrc" "$HOME/.bashrc"
ln -s "$DOTFILES/gitconfig" "$HOME/.gitconfig"
ln -s "$DOTFILES/init.vim" "$DOTCONFIG/nvim/init.vim"
ln -s "$DOTFILES/screenrc" "$HOME/.screenrc"
ln -s "$DOTFILES/vimrc" "$HOME/.vimrc"
ln -s "$DOTFILES/zshrc" "$HOME/.zshrc"

ZSHPLUGS=(
  "zsh-completions"
  "zsh-history-substring-search"
  "zsh-syntax-highlighting"
)

for INDEX in ${!ZSHPLUGS[*]}; do
  ZSHPLUG="${ZSHPLUGS[$INDEX]}"
  $GITCLONE "https://github.com/zsh-users/$ZSHPLUG.git" "$DOTLOCAL/$ZSHPLUG"
done

VIMPLUGS=(
  "scrooloose/nerdtree"
  "editorconfig/editorconfig-vim"
  "junegunn/goyo.vim"
  "junegunn/limelight.vim"
  "sheerun/vim-polyglot"
  "w0rp/ale"
)

for INDEX in ${!VIMPLUGS[*]}; do
  VIMPLUG="${VIMPLUGS[$INDEX]}"
  PLUGDIR=$(echo "$VIMPLUG" | cut -d '/' -f2)
  $GITCLONE "https://github.com/$VIMPLUG.git" "$HOME/.vim/pack/plugins/start/$PLUGDIR"
done

cp -r "$DOTFILES/vim/colors/" "$HOME/.vim/colors/"

cd "$HOME" || exit
rm -f "${HOME}/.zcompdump*"