#!/usr/bin/env bash

if [ -z "$HOME" ]; then echo "Seems you're \$HOMEless :("; exit 1; fi

DOTCONFIG=$HOME/.config
DOTFILES=$HOME/.dotfiles
DOTLOCAL=$HOME/.local/share/dotfiles
GITCLONE="git clone --depth=1"

# Remove existing files

rm -rf \
  "$DOTCONFIG/nvim/init.vim" \
  "$DOTLOCAL" \
  "$HOME/.bashrc" \
  "$HOME/.gitconfig" \
  "$HOME/.gitignore" \
  "$HOME/.profile" \
  "$HOME/.vim" \
  "$HOME/.vimrc" \
  "$HOME/.zshrc"

# Create folders

mkdir -p \
  "$DOTCONFIG/nvim" \
  "$DOTLOCAL" \
  "$HOME/.local/share/vim/"{swap,undo} \
  "$HOME/.vim/colors" \
  "$HOME/.vim/pack/plugins/start"

# Symlink files

ln -s "$DOTFILES/bashrc" "$HOME/.bashrc"
ln -s "$DOTFILES/gitconfig" "$HOME/.gitconfig"
ln -s "$DOTFILES/gitignore" "$HOME/.gitignore"
ln -s "$DOTFILES/init.vim" "$DOTCONFIG/nvim/init.vim"
ln -s "$DOTFILES/profile" "$HOME/.profile"
ln -s "$DOTFILES/vimrc" "$HOME/.vimrc"
ln -s "$DOTFILES/zshrc" "$HOME/.zshrc"

# Install zsh plugins

ZSHPLUGS=(
  "zsh-syntax-highlighting"
)

for INDEX in ${!ZSHPLUGS[*]}; do
  ZSHPLUG="${ZSHPLUGS[$INDEX]}"
  $GITCLONE "https://github.com/zsh-users/$ZSHPLUG.git" "$DOTLOCAL/$ZSHPLUG"
done

rm -f "${HOME}/.zcompdump*"

# Install vim plugins & colors

VIMPLUGS=(
  "editorconfig/editorconfig-vim"
  "scrooloose/nerdtree"
  "sheerun/vim-polyglot"
  "dense-analysis/ale"
)

for INDEX in ${!VIMPLUGS[*]}; do
  VIMPLUG="${VIMPLUGS[$INDEX]}"
  PLUGDIR=$(echo "$VIMPLUG" | cut -d '/' -f2)
  $GITCLONE "https://github.com/$VIMPLUG.git" "$HOME/.vim/pack/plugins/start/$PLUGDIR"
done

cp -r "$DOTFILES/vim/colors/" "$HOME/.vim/colors/"

